version: '3.6'

services:
  chatgpt:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules/
    ports:
      - 3000:3000
    env_file: ./.env.local
